cb:
    aws:
        ami:
            map: ap-northeast-1:ami-4ea78120,ap-southeast-1:ami-babd7bd9,ap-southeast-2:ami-9188d6f2,eu-central-1:ami-1cedfe70,eu-west-1:ami-24a47c57,sa-east-1:ami-6408b308,us-east-1:ami-2393ed49,us-west-1:ami-4af49b2a,us-west-2:ami-203c2a41
    openstack:
        image: cb-centos71-amb212-2015-10-27

    gcp:
        image: sequenceiqimage/cb-centos71-amb212-2015-10-279.tar.gz

    azure:
        rm:
            image:
                uri: >
                    East Asia:https://sequenceiqeastasia.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    East US:https://sequenceiqeastus.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    Central US:https://sequenceiqcentralus.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    North Europe:https://sequenceiqnortheurope.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    South Central US:https://sequenceiqsouthcentralus.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    North Central US:https://sequenceiqnorthcentralus.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    East US 2:https://sequenceiqeastus2.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    Japan East:https://sequenceiqjapaneast.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    Japan West:https://sequenceiqjapanwest.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    Southeast Asia:https://sequenceiqsoutheastasia.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    West US:https://sequenceiqwestus.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    West Europe:https://sequenceiqwesteurope.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd,
                    Brazil South:https://sequenceiqbrazilsouth.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd
        classic:
            image:
                uri: https://102589fae040d8westeurope.blob.core.windows.net/images/cb-centos71-amb212-2015-10-296_2015-October-29_13-7-os-2015-10-29.vhd
    threadpool:
        core:
            size: 40
        capacity:
            size: 4000
    intermediate:
        threadpool:
            core:
                size: 40
            capacity:
                size: 4000
    container:
        threadpool:
            core:
                size: 40
            capacity:
                size: 4000
    cert:
        dir: /certs/
    tls:
        private:
            key:
                file: client-key.pem
        cert:
            file: client.pem
    smtp:
        sender:
            host:
            port: 25
            username:
            password:
            from: no-reply@sequenceiq.com
    db:
        env:
            user: postgres
            pass:
            db: postgres
    aws:
        spotinstance:
            enabled: false
        external:
            id: provision-ambari
        cf:
            template:
                path: templates/aws-cf-stack.ftl
    blueprint:
        defaults: hdp-small-default,hdp-spark-cluster,hdp-streaming-cluster
    template:
        default: minviable-gcp,minviable-azure,minviable-aws
    mail:
        smtp:
            auth: true
            type: smtp
        starttls:
            enable: true
    success:
        cluster:
            installer:
                mail:
                    template:
                        path: templates/cluster-installer-mail-success.ftl
    failed:
        cluster:
            installer:
                mail:
                    template:
                        path: templates/cluster-installer-mail-fail.ftl
    container:
        orchestrator: SWARM
    supported:
        container:
            orchestrators: com.sequenceiq.cloudbreak.orchestrator.swarm.SwarmContainerOrchestrator
    docker:
        container:
            ambari:
                simple: sequenceiq/ambari:2.1.2-v4
                warmup: sequenceiq/ambari:2.1.2-v4
                db: postgres:9.4.1
            registrator: sequenceiq/registrator:v5.2
            docker:
                consul:
                    watch:
                        plugn: sequenceiq/docker-consul-watch-plugn:1.0
            kerberos: sequenceiq/kerberos:2.1.0-consul
            logrotate: sequenceiq/logrotate:v0.5.1
            munchausen: sequenceiq/munchausen:0.5.5
        relocate: true
    arm:
        central:
            storage: cbstore
        template:
            path: templates/arm-v2.ftl
        parameter:
            path: templates/parameters.ftl
    openstack:
        heat:
            template:
                path: templates/openstack-heat.ftl
        api:
            debug: false
    eventbus:
        threadpool:
            core:
                size: 100
    cloud:
        api:
            executorservice:
                pool:
                    size: 40
    max:
        azure:
            resource:
                name:
                    length: 50
        gcp:
            resource:
                name:
                    length: 63
        aws:
            resource:
                name:
                    length: 50
        openstack:
            resource:
                name:
                    length: 120
    address:
        resolving:
            timeout: 60000
    platform:
        default:
            variants: OPENSTACK:HEAT